In [14]:
import numpy as np
import pandas as pd

index=pd.MultiIndex.from_product([[2020,2021,2022],[1,2,3]],  
                                 names=['Năm','Lần thi'])

columns=pd.MultiIndex.from_product([['Bình','Lan','Vân'],['Toán','Lý','Hoá']],  
                                  names=['học sinh','môn học'])

#Taọ dữ liệu mẫu, là mảng kích thước 9x9 với các giá trị ngẫu nhiên từ 5-10
data=np.random.randint(5,10,(9,9))
#Taọ data frame
score=pd.DataFrame(data,index=index,columns=columns)
score

học sinh     Bình         Lan         Vân
môn học      Toán Lý Hoá Toán Lý Hoá Toán Lý Hoá
Năm  Lần thi
2020 1          5  9   9    9  5   7    7  8   6
     2          9  6   8    5  7   6    5  6   9
     3          5  7   8    5  7   8    7  6   9
2021 1          9  8   6    6  6   5    6  7   6
     2          9  5   7    7  6   5    9  5   5
     3          8  7   8    5  7   9    9  9   8
2022 1          9  5   6    8  9   8    8  7   9
     2          8  7   5    5  5   9    5  5   5
     3          5  7   8    6  5   8    7  8   5

In [3]:
print("Điểm môn Toán của Lan:\n", score['Lan', 'Toán'],'\n')

Điểm môn Toán của Lan:
 Năm   Lần thi
2020  1          6
      2          8
      3          6
2021  1          9
      2          5
      3          8
2022  1          9
      2          8
      3          9
Name: (Lan, Toán), dtype: int64

In [12]:
print("Điểm môn Lý của Bình và Hóa của Vân:\n",
      score.loc[:,[('Bình','Lý'),('Vân','Hóa')]],'\n')

TypeError: unhashable type: 'list'

In [6]:
print("Điểm môn Lý của Vân năm 2021:\n",score.loc[2021,('Vân','Lý')])

Điểm môn Lý của Vân năm 2021:
 Lần thi
1    5
2    6
3    8
Name: (Vân, Lý), dtype: int64

In [ ]:
print("\nĐiểm Toán của Bình và Hóa của Lan trong năm 2020, 2021:\n",  score.loc[[2020,2021],score[('Bình','Toán'),('Lan','Hóa')]],'\n')

In [9]:
print("Các lần thi học phần Lý mà Lan đạt điểm trên 7:\n",
 score['Lan','Lý'][score['Lan','Lý']>7])

Các lần thi học phần Lý mà Lan đạt điểm trên 7:
 Năm   Lần thi
2020  1          8
      2          9
2021  2          9
2022  1          8
Name: (Lan, Lý), dtype: int64

tính tb ddiemr từng môn học

In [18]:
score.groupby(level='Năm').mean()

học sinh      Bình                           Lan                      \
môn học       Toán        Lý       Hoá      Toán        Lý       Hoá
Năm
2020      6.333333  7.333333  8.333333  6.333333  6.333333  7.000000
2021      8.666667  6.666667  7.000000  6.000000  6.333333  6.333333
2022      7.333333  6.333333  6.333333  6.333333  6.333333  8.333333

học sinh       Vân
môn học       Toán        Lý       Hoá
Năm
2020      6.333333  6.666667  8.000000
2021      8.000000  7.000000  6.333333
2022      6.666667  6.666667  6.333333

tính tb từng lần thi

In [24]:
#score.groupby(level='môn học',axis=1).mean()
score.T.groupby(level='môn học').mean().T

môn học            Hoá        Lý      Toán
Năm  Lần thi
2020 1        7.333333  7.333333  7.000000
     2        7.666667  6.333333  6.333333
     3        8.333333  6.666667  5.666667
2021 1        5.666667  7.000000  7.000000
     2        5.666667  5.333333  8.333333
     3        8.333333  7.666667  7.333333
2022 1        7.666667  7.000000  8.333333
     2        6.333333  5.666667  6.000000
     3        7.000000  6.666667  6.000000